[package]
authors = ["louisfd <louisfd94@gmail.com>"]
categories = ["science"]
description = "Candle backend for the Burn framework"
edition = "2021"
keywords = ["deep-learning", "machine-learning", "data"]
license = "MIT OR Apache-2.0"
name = "burn-candle"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-candle"
version = "0.9.0"

[features]

[dependencies]
derive-new = { workspace = true }
burn-tensor = { path = "../burn-tensor", version = "0.9.0" }
half = { workspace = true, features = ["std"] }
# candle-core = { version = "0.1.2" }
candle-core = { git = "https://github.com/huggingface/candle", branch = "main" }

[dev-dependencies]
burn-autodiff = { path = "../burn-autodiff", version = "0.9.0", default-features = false, features = [
    "export_tests",
] }
burn-tch = { path = "../burn-tch", version = "0.9.0", default-features = false, features = [
] }
burn-tensor = { path = "../burn-tensor", version = "0.9.0", default-features = false, features = [
    "export_tests",
] }
